### ISSUE TITLE
 입력기 설정이 나오지 않습니다. 

### ISSUE THREAD

**Issue by narusas** [kiding/SokIM#22]
1. 사용하고 계신 속 입력기 버전
1.1.2
1. 문제가 발생한 앱 이름
 일반
1. 자세한 문제 재현 방법

설치후  3벌씩 지원여부등을 확인하기 위해 속 설정 메뉴가 있나 확인했습니다만 어떤 메뉴도 나오지 않습니다. 

상태바의     S    아이콘을 우클릭,  opt click등을 해봐도 
![스크린샷 2023-10-17 오전 9 43 30](https://github.com/kiding/SokIM/assets/1133479/21cd39c6-f504-4e3d-89cd-3fdf14c5d276)

이 화면이 전부입니다. 

키보드 설정에서도 
![스크린샷 2023-10-17 오전 9 44 10](https://github.com/kiding/SokIM/assets/1133479/9f43d57f-cb33-4e0b-9e04-a64bb2589352)

이것만 나옵니다. 

1. 디버그 메시지
> [디버그 메시지 보기](https://github.com/kiding/SokIM#디버그-메시지-보기) 부분을 참조해
 주세요.

**Comment by narusas** [comment]
설치 제거후 재기동후 재설치 하니 메뉴가 나옵니다. 
![스크린샷 2023-10-17 오전 10 24 38](https://github.com/kiding/SokIM/assets/1133479/83f713d7-8024-4c62-b942-a2933195791a)


혹시 3벌씩 지원은 아직 않되는 상태일까요?

**Comment by kiding** [comment]
안녕하세요! 문제가 해결되었다니 다행입니다. 

세벌식은 기능 준비 중에 있습니다. 언제 출시할 수 있을지는 아직 말씀드리기가 어렵네요.

감사합니다!
