### ISSUE TITLE
Credential Field에서 이용할 수 없는 문제

### ISSUE THREAD

**Issue by Taewan-P** [kiding/SokIM#28]
안녕하세요,

현재 Sok입력기가 Credential Field에서는 강제로 비활성화되어 mac의 기본 영어 입력기로 변경되는 현상이 있는데, 이를 지원할 수 있을까요?

매번 비밀번호만 입력하면 입력기를 바뀌는 문제가 있습니다.

기본 영어 입력기를 아에 지우고 Sok만 쓰고 싶은데, 기본 영어 입력기를 지우면 Input Source가 Sok으로 선택된 상황에서는 아예 Credential Field에서는 입력이 되지 않습니다.

<img width="218" alt="image" src="https://github.com/kiding/SokIM/assets/27392567/183e8f96-faa8-4237-8d94-cbabb3716084">

**Comment by Taewan-P** [comment]
#20 에서 언급된 문제네요. 이슈 닫겠습니다.

**Comment by kiding** [comment]
감사합니다. 기본값을 바꿔야겠다고 생각했는데 잊고 있었네요… 😅
