### ISSUE TITLE
Caps Lock 고정 관련

### ISSUE THREAD

**Issue by i-sumin** [kiding/SokIM#3]
안녕하세요.
먼저 좋은 프로그램 만들어주셔서 정말 감사합니다.
덕분에 한-영 전환에서 속이 뻥 뚫리는 속도를 체감하게 되어서 너무 기쁩니다.

다름이 아니라 Caps Lock 고정을 통해 영문을 대문자로 입력할 순 없는건가요?
⌘+CapsLock이나, ⌥+CapsLock, ⌃+CapsLock은 도통 먹히지 않네요. 구조상 어쩔 수 없는 문제일까요?

**Comment by kiding** [comment]
안녕하세요. Caps Lock 기능을 구현하여 [v1.1.0 (19)](https://github.com/kiding/SokIM/releases/tag/v1.1.0)로 선공개하였습니다. 시간이 되신다면 테스트와 피드백 부탁드립니다. 감사합니다.

한/A 전환을 Caps Lock으로 사용하시는 경우 macOS 내장과 동일하게 Caps Lock 키를 오래 누르고 있으면 Caps Lock 기능이 활성화됩니다.

**Comment by i-sumin** [comment]
안녕하세요. 피드백을 통해 기능을 구현해주셔서 감사합니다.

우선 v1.1.0 (19) 버전이 출시되고 며칠동안 사용하였는데 다음과 같은 문제점이 있었습니다.

한글 자판 모드에서도 캡스락 모드가 적용되는 문제(?)가 있습니다.
한글 자판으로 변경 후 캡스락을 길게 누르면, 캡스락 키에 점등이 되고 캡스락 모드가 되는데..
한글 자판 모드에서는 해당 기능이 적용이 안되도록 해도 좋을것 같습니다!

**Comment by kiding** [comment]
한/A 전환이 Caps Lock인 경우 Caps Lock 활성화 시 영문 입력으로 자동 선택 되도록 하는 수정을 [v1.1.1 (22)](https://github.com/kiding/SokIM/releases/tag/v1.1.1)에 적용하여 선공개하였습니다. 시간이 되신다면 테스트와 피드백 부탁드립니다. 감사합니다.
