### ISSUE TITLE
안녕하세요... 죄송합니다만 사용법 자체를 모르겠습니다.

### ISSUE THREAD

**Issue by Ma-rk** [kiding/SokIM#33]
안녕하세요, 
맥에서 한/영 전환이 너무 불편해서 방법을 찾다가 속 입력기를 발견하고 설치해봤습니다.
그런데 사용방법을 모르겠습니다.
설치해서 세팅하고 나니까 일단 cabslock으로 입력전환이 안되고...
어디로 들어가서 무슨 설정을 변경해야 하는건지,
속입력기로 한영 전환은 무슨 키를 눌러야 하는건지 사용법을 모르겠어요.
검색도 해봤지만 마땅한 정보를 찾을 수 없었기에
사용방법을 여쭤보고자 글을 남겨봅니다.
감사합니다.

**Comment by kiding** [comment]
안녕하세요, 혹시 #22 와 유사한 문제이실까요? 

매뉴얼 쪽이 아직 미흡합니다. 아직 기능이랄 게 많지 않아 여러모로 준비 중에 있습니다.
