### ISSUE TITLE
한/영 전환 키를 오른쪽 Command 키로 바꾸었을 때의 Caps lock.

### ISSUE THREAD

**Issue by suk-6** [kiding/SokIM#6]
1. 사용하고 계신 속 입력기 버전
v1.0 (15)

2. 자세한 문제 재현 방법
오른쪽 Command 키를 한/영 전환 키로 사용 시,
Caps lock을 눌렀을 때 대문자로 고정되지 않고, 키보드에 Light만 들어옴.<br>
이슈들을 보니, Caps lock이 고정되지 않는 이슈가 있던데
아마 그 이슈랑 같은 이슈이지 않을까.. 생각됩니다.

3. 디버그 메시지
`SokIM[2696:56e8e7] SokIM/Helpers.swift: setKeyboardCapsLock(enabled:) IOHIDManagerOpen 실패`

**Comment by kiding** [comment]
https://github.com/kiding/SokIM/issues/3#issuecomment-1703972681 와 함께 해결되었습니다. 감사합니다.
