### ISSUE TITLE
기존 내장 키보드 입력기보다 얼마나 빨라진 것인지 궁금합니다

### ISSUE THREAD

**Issue by roeniss** [kiding/SokIM#7]
우선 이 프로젝트를 (마침내!) 릴리즈 하셨다는 부분에 대하여 대단히 존경스럽다는 말씀을 드리고, 또한 이 글이 비난이나 조롱의 의도가 아님을 명백하게 밝히고 글을 이어나가겠습니다.

현재 저는 아래 스크린샷과 같은 세팅을 사용하고 있는데요, SokIM 이 없이도 [영상](https://twitter.com/kid1ng/status/1513856407103492097)에 나온 타이핑을 동일하게 재현할 수 있었습니다.

<img width="719" alt="Screenshot 2023-04-21 at 02 26 23 by seonghyeok" src="https://user-images.githubusercontent.com/26613280/233442381-6034ec8e-4e55-418d-8c81-a400971f6a4a.png">

<img width="706" alt="Screenshot 2023-04-21 at 02 26 42 by seonghyeok" src="https://user-images.githubusercontent.com/26613280/233442481-2bc7fd37-c460-4ffa-b81d-618f97c9fcd4.png">

(Karabiner-elements 를 이용해, right_command 를 F19로 맵핑하였습니다)

1년전 영상이라 그런지, 2분짜리 동영상이 계속 무한로딩에 빠지는 바람에 모든 장면을 재현해보진 못했는데요, 위 세팅으로 제가 느끼는 밀림 현상은 해소되었기 때문에

1. SokIM 은 위 세팅보다도 더 빠른 것인지
2. 그렇다면 얼마나 빠른것인지 (혹은 이 속도를 측정할 수 있는 방법 같은게 있는지)

궁금합니다.

다시 한 번, 정식 릴리즈 축하드립니다!

**Comment by kiding** [comment]
안녕하세요. 프로젝트에 관심을 가져주셔서 감사합니다.

1-1. macOS 기본 한영 전환과 속 입력기의 한영 전환은 구조적으로 다른 부분이 있습니다. macOS의 경우 한글 입력기와 영문 입력기 두가지 다른 프로세스가 서로 전환되는 구조입니다만, 속 입력기는 프로세스 한개 안에서 상태만 변하고 영문과 한글을 둘 다 입력할 수 있는 구조를 가지고 있습니다. 이는 프로세스가 전환되는 과정에서 생기는 여러가지 오버헤드의 영향을 받지 않기 때문에 기존보다 빠르게 전환할 수 있게 됩니다.

1-2. 속 입력기는 다른 입력기처럼 InputMethodKit API를 사용하고 있지만 이와 함께 USB HID 입력을 직접 가져와 사용하고 있습니다. InputMethodKit은 시스템이 키보드 입력을 해석하고 다시 입력기로 정보를 내려보내주는 과정이 있으나, 이 대신 속 입력기는 키보드 입력을 바로 제공 받아 직접 해석하고 한영 전환을 실시하게 됩니다. 이렇기 때문에 거의 오버헤드가 없는 한영 전환이 가능하게 됩니다.

1-3. 한국어와 영어 외에 다른 언어를 같이 사용하는 경우에 도움이 됩니다. 저와 주변인의 경우 일본어를 추가로 사용하고 있는데, 속 입력기를 사용하여 Caps Lock 키로 한<->영 전환을 하고, macOS의 "입력 메뉴에서 다음 소스 선택"에 Command+Space를 배정하여 한<->일 전환을 하는 등 편리하게 사용하고 있습니다.

2. 속도를 측정할 수 있는 방법에 대해서는 아직 객관적인 방법을 찾지는 못했습니다. "ㅁaㅁaㅁaㅁaㅁaㅁa..."를 얼마나 빠르고 문제 없이 입력할 수 있는지 정도...가 있을 것 같습니다.
