### ISSUE TITLE
pkg 파일로 설치 완료 후, 시스템 설정으로 권한 허용하려고 하나 "속 입력기"가 보이지 않습니다.

### ISSUE THREAD

**Issue by dennis-zent** [kiding/SokIM#8]
pkg 파일로 설치 완료 후, 시스템 설정으로 권한 허용하려고 하나 "속 입력기"가 보이지 않습니다.

"응용 프로그램"을 기본 위치로 보여주는데 거기에는 없습니다.

설치된 위치를 따로 지정해서 찾아야 하나요?

운영체제: 13.2.1(22D68)

**Comment by kiding** [comment]
안녕하세요, 잘 지내시지요?

1. 시스템 설정 → 키보드 → 입력 소스 "편집..." 버튼 → "+" 버튼 → 영어 → "속" → "추가" 버튼으로 추가한 이후 입력기를 바꿔주어야 권한을 묻는 과정이 실행됩니다. 혹시 보이시지 않으면 시스템 재시동을 부탁드립니다. 자세한 설치 방법은 README.md를 참고해 주세요.
2. 설치된 위치는 `/Applications`가 아닌 `/Library/Input Methods`에 있습니다.

**Comment by dennis-zent** [comment]
네, 잘 지내고 있습니다. ^^;;

입력기를 바꿔주니 권한 묻는 과정이 실행됩니다. 설치된 위치 변경해서 지정하는 것 성공했습니다.

잘 쓰겠습니다.
